import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;


public class home extends javax.swing.JFrame implements ActionListener {

    // Variables declaration
    private JCheckBox[] boxes;
    private javax.swing.JCheckBox directorCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextArea userDisplay;
    private javax.swing.JTextField userInput;
    private int checkboxFlag = 0;
    private Boolean directorFlag = false;
    private Boolean singleNumberRating = false;

    final String emptySearchResult = "## You caused the program to shit the bed good going dumbass,\n" +
            "## One of the following is the reason why:\n" +
            "## A: The Person you searched is not on the TMDB database.\n" +
            "## B: You cant spell for shit (Most likely the reason)";


    /**
     * Creates new form NewJFrame
     */
    public home() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        userInput = new javax.swing.JTextField();
        directorCheck = new javax.swing.JCheckBox();
        boxes = new javax.swing.JCheckBox[11];
        jScrollPane1 = new javax.swing.JScrollPane();
        userDisplay = new javax.swing.JTextArea();
        searchButton = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(23, 35, 55));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 510));

        jPanel1.setBackground(new java.awt.Color(62, 120, 207));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Mean Movie Adviser ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(219, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(228, 228, 228))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 780, 70));

        jPanel2.setBackground(new java.awt.Color(113, 168, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Director ??");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter the fuckers name:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("What range range is your shitty taste:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Choose one/two numbers e.g. 10/6-10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addContainerGap(16, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addContainerGap(226, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 260, 440));

        jPanel4.setBackground(new java.awt.Color(245, 247, 253));

        userInput.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        userInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userInput.setText("Cunts Name");
        userInput.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (userInput.getText().equals("Cunts Name")) {
                    userInput.setText("");
                    userInput.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (userInput.getText().isEmpty()) {
                    userInput.setForeground(Color.GRAY);
                    userInput.setText("Cunts Name");
                }
            }
        });

        directorCheck.setBackground(new java.awt.Color(245, 247, 253));
        directorCheck.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        directorCheck.setText("Did they Direct movies u stupid Cunt");
        directorCheck.addActionListener(this);
        directorCheck.setActionCommand("Director");

        for (int i = 0; i < boxes.length; i++) {
            boxes[i] = new JCheckBox();
            boxes[i].setBackground(new java.awt.Color(245, 247, 253));
            boxes[i].setText(Integer.toString(i));
            boxes[i].addActionListener(this);
            boxes[i].setActionCommand(Integer.toString(i));
        }

        userDisplay.setColumns(20);
        userDisplay.setRows(5);
        userDisplay.setText("Text will magically appear here if you're retarded");
        userDisplay.setEditable(false);
        jScrollPane1.setViewportView(userDisplay);

        searchButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(this);
        searchButton.setActionCommand("search");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userInput, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[0])
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[1], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[2])
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[3])
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[4])
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[5])
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[6])
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[7])
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[8])
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[9])
                                                                .addGap(15, 15, 15)
                                                                .addComponent(boxes[10])))
                                                .addContainerGap(13, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                                .addComponent(directorCheck)
                                                                .addGap(135, 135, 135))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(177, 177, 177))))))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(directorCheck)
                                .addGap(56, 56, 56)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(boxes[0])
                                        .addComponent(boxes[1])
                                        .addComponent(boxes[2])
                                        .addComponent(boxes[3])
                                        .addComponent(boxes[4])
                                        .addComponent(boxes[5])
                                        .addComponent(boxes[6])
                                        .addComponent(boxes[7])
                                        .addComponent(boxes[8])
                                        .addComponent(boxes[9])
                                        .addComponent(boxes[10]))
                                .addGap(56, 56, 56)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 520, 440));

        pack();
        this.setLocationRelativeTo(null);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        home start = new home();
        start.setVisible(true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        int checkCount = 0;
        int low = 0;
        int high = 10;
        String error;
        String cmd = e.getActionCommand();

        switch (cmd) {
            case "0":
            case "1":
            case "2":
            case "3":
            case "4":
            case "5":
            case "6":
            case "7":
            case "8":
            case "9":
            case "10":
                for (JCheckBox box : boxes) {
                    if (box.isSelected())
                        checkCount += 1;
                }
                if (checkCount > 2) {
                    boxes[checkboxFlag].setSelected(false);
                    singleNumberRating = false;
                } else if (checkCount == 1) {
                    singleNumberRating = true;
                }
                checkboxFlag = Integer.parseInt(cmd);
                break;
            case "Director":
                directorFlag = !directorFlag;
                //userDisplay.setText(Boolean.toString(directorFlag));
                break;
            case "search":
                meanMovieAdviser prick = new meanMovieAdviser();
                Person person;
                Result[] result;

                for (int i = 0; i < boxes.length; i++) {
                    if (boxes[i].isSelected() && singleNumberRating) {
                        high = i;
                        low = i;
                    } else if (boxes[i].isSelected() && checkCount == 0) {
                        low = i;
                        checkCount += 1;
                    } else if (boxes[i].isSelected() && checkCount == 1) {
                        high = i;
                    }
                }

                error = prick.personsName(userInput.getText());
                if (error == null) {
                    if (prick.personSearch(prick.getName()) != null) {
                        result = prick.personSearch(prick.getName());
                        if (result.length == 1) {
                            person = prick.mapPerson(Integer.toString(result[0].getId()));
                            prick.printCast(person.getCast());
                            new displayForm(person, directorFlag, low, high);
                            this.setVisible(false);
                        } else {
                            new resultChoice(result, prick, directorFlag, low, high);
                            this.setVisible(false);
                        }
                    } else
                        userDisplay.setText(emptySearchResult);
                } else {
                    userDisplay.setText(error);
                    break;
                }
                break;
            default:
                throw new IllegalStateException("Unexpected value: " + cmd);
        }
    }
}
